# Uncomment this line to define a global platform for your project
platform :ios, "6.1"

target "Liger" do
       pod 'LigerMobile', path: './..'

       pod 'Cordova', '3.1.0'
       pod 'UIColor-HTMLColors', '1.0.0'
end

target "LigerTests" do
       pod 'OCMock', '2.2.3'
end

