# Uncomment this line to define a global platform for your project
platform :ios, "6.1"

target "Liger" do
       pod 'LigerMobile', path: './..'
end

target "LigerTests" do
       pod 'OCMock', '2.2.4'
end

